### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by ThreeDeeJay** [linusced/audio_synthesizer#1]
Hi there, I've been looking for an app to test MIDI with OpenAL Soft, so this app looks perfect!
However, I don't see the compiled binaries. Are there Win32 binaries available for download anywhere?

**Comment by linusced** [comment]
Hi!
There currently are not any downloadable binaries/executables for this project for windows. I don't have a windows pc but I will in the near future try to start making my projects cross platform by using windows in a virtual machine.
Sorry about this.

And this project is very outdated compared to my other projects so I'm currently working on an updated version where I use cmake and better c++ code. So maybe when I'm done with that I can make it work on multiple operating systems.

**Comment by ThreeDeeJay** [comment]
That's unfortunate but I'll keep an eye on possible new releases.
Thanks for the quick response tho! 👍
